#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 14 01:09:42 2018

@author: emilykilen
"""


import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
import matplotlib.colors as colors
from mpl_toolkits.mplot3d import Axes3D
#25micron Volume

def prod(nums):
    return(nums[0]*nums[1]*nums[2])

size = (528,320,456)
#VOL = #D matrix of atlas Nissl volume

with open('/Users/emilykilen/anaconda3/HeilbronnerData/atlasVolume/atlasVolume.raw', 'r') as file:
    VOL = np.fromfile(file, dtype = np.dtype('<u1'))
file.close()


VOL = np.reshape(VOL, size, order='F')

with open('/Users/emilykilen/anaconda3/HeilbronnerData/annotation/annotation.raw', 'r') as file:
    ANO = np.fromfile(file, dtype='<u4')
file.close()
ANO = np.reshape (ANO,size, order='F')


plt.figure(1)  
plt.imshow(VOL[264,:,:], cmap="gray");
plt.colorbar()
plt.show()
plt.savefig('figure1.png')

plt.figure(2)  
plt.imshow(ANO[264,:,:], cmap = "Accent", norm=colors.LogNorm(vmin=1, vmax=10000));

plt.colorbar()
plt.show()
plt.savefig('figure2.png')

plt.figure(3)  
plt.imshow(VOL[:,:,220], cmap="gray");
plt.colorbar()
plt.show()
plt.savefig('figure3.png')

plt.figure(4)  
plt.imshow(ANO[:,:,220], cmap = "Accent", norm=colors.LogNorm(vmin=1, vmax=10000));
plt.colorbar()
plt.show()
plt.savefig('figure4.png')